services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=k8s-test'
      - 'POSTGRES_PASSWORD=postgrespassword24'
      - 'POSTGRES_USER=postgres'
#    volumes:
#      - /private/var/lib/postgresql:/var/lib/postgresql
    volumes:
#      - pgdata:/var/lib/postgresql/data
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
##  volumes:
##    postgres-data:
##      driver: local
#  volumes:
#    pgdata:

#docker run --name k8s-test -e POSTGRES_PASSWORD=postgrespassword24 -p 5432:5432 -d postgres
# docker run -it --name dbgate-instance --restart always -p 3000:3000 dbgate/dbgate
